configs:
  avhrr:
    grid_file: avhrr_geotiff_grids.grd
    p2g_args: --tiled --compress DEFLATE
    save:
    - '*.tif'
    tasks:
    - acspo2gtiff.sh --grid-coverage 0 -p sst -g alaska_1000 --dtype real4 --output-pattern
      {satellite}_{instrument}_{product_name}_{begin_time}_{grid_name}.float.tif
    - acspo2gtiff.sh --grid-coverage 0 -p sst -g alaska_overview --output-pattern
      {satellite}_{instrument}_{product_name}_{begin_time}_{grid_name}.tif
  modis:
    grid_file: modis_geotiff_grids.grd
    p2g_args: --tiled --compress DEFLATE
    save:
    - '*.tif'
    tasks:
    - acspo2gtiff.sh --grid-coverage 0 -p sst -g alaska_500 --dtype real4 --output-pattern
      {satellite}_{instrument}_{product_name}_{begin_time}_{grid_name}.float.tif
    - acspo2gtiff.sh --grid-coverage 0 -p sst -g alaska_overview --output-pattern
      {satellite}_{instrument}_{product_name}_{begin_time}_{grid_name}.tif
  viirs:
    grid_file: viirs_geotiff_grids.grd
    p2g_args: --tiled --compress DEFLATE
    save:
    - '*.tif'
    tasks:
    - acspo2gtiff.sh --grid-coverage 0 -p sst -g alaska_300 --dtype real4 --output-pattern
      {satellite}_{instrument}_{product_name}_{begin_time}_{grid_name}.float.tif
    - acspo2gtiff.sh --grid-coverage 0 -p sst -g alaska_overview --output-pattern
      {satellite}_{instrument}_{product_name}_{begin_time}_{grid_name}.tif
limits:
  processor: 2
