configs:
  aqua:
    bias: /opt/cspp/bias
    driver: '/cspp/CSPP_ACSPO_2_0/scripts/run_acspo.bash --dynanc=/cspp/dyno/sst '
    options: '-p 2 -s aqua -vv '
    save:
    - '*.nc'
  metopb:
    bias: /opt/cspp/bias
    driver: '/cspp/CSPP_ACSPO_2_0/scripts/run_acspo.bash  '
    options: ' -p 2 -s metopb --dynanc=/cspp/dyno/sst '
    save:
    - '*.nc'
  metopc:
    bias: /opt/cspp/bias
    driver: '/cspp/CSPP_ACSPO_2_0/scripts/run_acspo.bash  '
    options: ' -p 2 -s metopc --dynanc=/cspp/dyno/sst '
    save:
    - '*.nc'
  n18:
    bias: /opt/cspp/bias
    driver: '/cspp/CSPP_ACSPO_2_0/scripts/run_acspo.bash --dynanc=/cspp/dyno/sst '
    options: '-p 2 -s n18 -vv '
    save:
    - '*.nc'
  n19:
    bias: /opt/cspp/bias
    driver: '/cspp/CSPP_ACSPO_2_0/scripts/run_acspo.bash --dynanc=/cspp/dyno/sst '
    options: ' -p 2 -s n19 -vv '
    save:
    - '*.nc'
  noaa20:
    bias: /opt/cspp/bias
    driver: '/cspp/CSPP_ACSPO_2_0/scripts/run_acspo.bash  '
    options: ' -p 2 -s n20 --dynanc=/cspp/dyno/sst '
    save:
    - '*.nc'
  npp:
    bias: /opt/cspp/bias
    driver: '/cspp/CSPP_ACSPO_2_0/scripts/run_acspo.bash  '
    options: ' -p 2 -s npp --dynanc=/cspp/dyno/sst '
    save:
    - '*.nc'
  terra:
    bias: /opt/cspp/bias
    driver: '/cspp/CSPP_ACSPO_2_0/scripts/run_acspo.bash --dynanc=/cspp/dyno/sst '
    options: ' -p 2 -s terra -vv '
    save:
    - '*.nc'
