configs:
  default:
    grid: 203
    options: '--grid-coverage 0 --output-pattern UAF_AWIPS_{satellite}_{instrument}_{product_name}_{grid_name}_{begin_time}
      --source-name UAF '
    p2g_config: uaf_awips_backend.ini
    save:
    - '*'
driver: acspo2awips.sh
limits:
  processor: 2
