driver: polar2grid.sh
configs:
  viirs:
   options: " --sector-id Polar --letters --compress --fix-awips --output-pattern 'UAF_AII_{satellite}_{instrument}_{product_name}_{sector_id}_{tile_id}_{begin_time:%Y%m%d_%H%M}.nc' "
   save: 
     - "UAF_AII_*.nc"
   p2g_config: "scmi_backend.ini"
   p2g_grid: "scmi_grids.conf"
   tasks:
     viirs_sdr: 
       ibands:
         grid: polar_alaska_300
         bands:  "i01 i02 i03 i04 i05"
       mbands:
         grid: polar_alaska_700
         bands: "m03 m04 m05 m07 m09 m10 m11 m12 m13 m14 m15 m16 dynamic_dnb dnb adaptive_dnb hncc_dnb"
     crefl:
       mbands:
         grid: polar_alaska_700
         bands: "viirs_crefl03 viirs_crefl04"
       ibands: 
         grid: polar_alaska_300
         bands: "viirs_crefl08 viirs_crefl09 viirs_crefl10 "
limits:
  processor: 2
