driver: polar2grid.sh
configs:
  viirs:
   options: " --sector-id Polar --letters --compress --fix-awips --output-pattern 'UAF_AII_{satellite}_{instrument}_{product_name}_{sector_id}_{tile_id}_{begin_time:%Y%m%d_%H%M}.nc' "
   save: 
     - "UAF_AII_*.nc"
   p2g_config: "scmi_backend.ini"
   p2g_grid: "scmi_grids.conf"
   tasks:
     viirs_sdr: 
       ibands:
         grid: polar_alaska_300
         bands:  "i01 i02 i03 i04 i05 i_solar_zenith_angle i_sat_zenith_angle"
       mbands:
         grid: polar_alaska_700
         bands: "m03 m04 m08 m09 m10 m11 m12 m13 m14 m15 m16 dynamic_dnb dnb adaptive_dnb hncc_dnb m_solar_zenith_angle m_sat_zenith_angle"
     crefl:
       mbands:
         grid: polar_alaska_700
         bands: "viirs_crefl03 viirs_crefl04"
  modis:
   options: " --sector-id Polar --letters --compress --fix-awips --output-pattern 'UAF_AII_{satellite}_{instrument}_{product_name}_{sector_id}_{tile_id}_{begin_time:%Y%m%d_%H%M}.nc' "
   save:
     - "UAF_AII_*.nc"
   p2g_config: "scmi_backend.ini"
   p2g_grid: "scmi_grids.conf"
   tasks:
     modis:
       qkm:
         grid: polar_alaska_250
         bands:  "vis01 vis02"
       hkm:
         grid: polar_alaska_500
         bands: "vis03 vis04 vis05 vis06 vis07"
       km:
         grid: polar_alaska_1km
         bands: "vis26 bt20 bt27 bt23 bt28 bt29 bt30 bt31 bt32 satellite_zenith_angle solar_zenith_angle"
     crefl:
       qkm:
         grid: polar_alaska_250
         bands: "modis_crefl01_250m modis_crefl02_250m"
       hkm:
         grid: polar_alaska_500
         bands: "modis_crefl03_500m modis_crefl04_500m modis_crefl05_500m modis_crefl06_500m "
  clavrx:
   options: " --sector-id Polar --letters --compress --fix-awips --grid-coverage 0.0001 --output-pattern '{satellite}_{instrument}_{product_name}_{sector_id}_{tile_id}_{begin_time:%Y%m%d_%H%M}.nc' "
   save:
     - "*.nc"
   p2g_config: "scmi_backend.ini"
   p2g_grid: "scmi_grids.conf"
   tasks:
     clavrx:
       qkm:
         grid: polar_alaska_700
         bands:  "cld_emiss_acha cld_height_acha cld_opd_dcomp cld_reff_dcomp cld_temp_acha cloud_phase cloud_type cld_height_base_acha rain_rate"
  avhrr:
    options: " --sector-id Polar --letters --compress --fix-awips --output-pattern 'UAF_AII_{satellite}_{instrument}_{product_name}_{sector_id}_{tile_id}_{begin_time:%Y%m%d_%H%M}.nc' "
    save:
     - "UAF_AII_*.nc"
    p2g_config: "scmi_backend.ini"
    p2g_grid: "scmi_grids.conf"
    tasks:
      avhrr:
        qkm:
          grid: polar_alaska_1km
          bands:  "band1_vis band2_vis band3a_vis band3b_bt band4_bt band5_bt "
  mirs:
    options: " --sector-id Polar --letters --compress --fix-awips --grid-coverage 0.00001 --output-pattern 'UAF_AII_{satellite}_{instrument}_{product_name}_{sector_id}_{tile_id}_{begin_time:%Y%m%d_%H%M}.nc' "
    save:
     - "UAF_AII_*.nc"
    p2g_config: "scmi_backend.ini"
    p2g_grid: "scmi_grids.conf"
    tasks:
      mirs:
        5km:
          grid: polar_alaska_5km
          bands:  " sfr rain_rate sea_ice snow_cover tpw swe clw btemp_23v btemp_183h1 "
  amsr2_l1b:
    options: " --sector-id Polar --letters --compress --fix-awips --grid-coverage 0.00001 --output-pattern 'UAF_AII_{satellite}_{instrument}_{product_name}_{sector_id}_{tile_id}_{begin_time:%Y%m%d_%H%M}.nc' "
    save:
     - "UAF_AII_*.nc"
    p2g_config: "scmi_backend.ini"
    p2g_grid: "scmi_grids.conf"
    tasks:
      amsr2_l1b:
        5km:
          grid: polar_alaska_5km
          bands:  "btemp_10.7h btemp_10.7v btemp_18.7h btemp_18.7v btemp_23.8h btemp_23.8v btemp_36.5h btemp_36.5v btemp_6.9h btemp_6.9v btemp_7.3h btemp_7.3v btemp_89.0ah btemp_89.0av btemp_89.0bh btemp_89.0bv "
limits:
  processor: 2
