configs:
  aqua:
    driver: 'run_clavrx.sh '
    options: ' 2 '
    save:
    - '*.hdf'
  avhrr:
    driver: 'run_clavrx.sh '
    options: ' 1 '
    save:
    - done/*.hdf
  modis:
    driver: 'run_clavrx.sh '
    options: ' 2 '
    save:
    - done/*.hdf
  n18:
    driver: 'run_clavrx.sh '
    options: ' 1 '
    save:
    - done/*.hdf
  n19:
    driver: 'run_clavrx.sh '
    options: ' 1 '
    save:
    - done/*.hdf
  npp:
    driver: 'run_clavrx.sh '
    options: ' -x -d 3 '
    save:
    - done/*.hdf
    - done/*log
    - work/*log
  terra:
    driver: 'run_clavrx.sh '
    options: ' 2 '
    save:
    - done/*.hdf
