configs:
  npp: 
   mapper:
     dnb: npp_viirs_adaptive_dnb_*_alaska_300.tif
     i01: npp_viirs_i01*_alaska_300.tif
     i02: npp_viirs_i02*_alaska_300.tif
     i03: npp_viirs_i03*_alaska_300.tif
     i04: npp_viirs_i04*_alaska_300.tif
     i05: npp_viirs_i05*_alaska_300.tif
     m02: npp_viirs_m02_*_alaska_600.tif
     m03: npp_viirs_m02_*_alaska_600.tif
     m04: npp_viirs_m02_*_alaska_600.tif
     m05: npp_viirs_m02_*_alaska_600.tif
     m06: npp_viirs_m02_*_alaska_600.tif
     m07: npp_viirs_m02_*_alaska_600.tif
     m08: npp_viirs_m02_*_alaska_600.tif
     m15: npp_viirs_m02_*_alaska_600.tif
     true_color: npp_viirs_true_color_*_alaska_300.tif
     crefl01: npp_viirs_viirs_crefl01_*_alaska_300.tif
     crefl03: npp_viirs_viirs_crefl03_*_alaska_300.tif
     crefl04: npp_viirs_viirs_crefl04_*_alaska_300.tif
     crefl08: npp_viirs_viirs_crefl08_*_alaska_300.tif
   single:
   - title: true_color
     band: true_color
     name: "npp.%y%j.%H%M_true_color"
   - title: dnb
     band: dnb
     name: "npp.%y%j.%H%M_DNB"
   - title: thermal
     band: "i05"
     name: "npp.%y%j.%H%M_I05"
   combinations:
   - title: landcolor
     bands:
       r: "i03"
       g: "i02"
       b: "i01"
     name: "npp.%y%j.%H%M_I03_I02_I01"
  t1:
   mapper:
     "30": terra_modis_bt30_*_alaska_1000.tif
     "31": terra_modis_bt31_*_alaska_1000.tif
     true_color: terra_modis_true_color_*_alaska_250.tif
     "1": terra_modis_vis01_*_alaska_250.tif
     "1_500": terra_modis_vis01_*_alaska_500.tif
     "2": terra_modis_vis02_*_alaska_250.tif
     "2_500": terra_modis_vis02_*_alaska_500.tif
     "3": terra_modis_vis03_*_alaska_500.tif
     "4": terra_modis_vis04_*_alaska_500.tif
     "5": terra_modis_vis05_*_alaska_500.tif
     "6": terra_modis_vis06_*_alaska_500.tif
     "7": terra_modis_vis07_*_alaska_500.tif
   single:
   - title: true_color
     band: true_color
     name: "t1.%y%j.%H%M_true_color"
   - title: thermal
     band: "31"
     name: "t1.%y%j.%H%M_31"
   combinations:
   - title: 261
     bands:
       r: "2_500"
       g: "6"
       b: "1_500"
       p: "1"
     name: "t1.%y%j.%H%M_2_6_1_1"
   - title: 721
     bands:
       r: "7"
       g: "2_500"
       b: "1_500"
       p: "1"
     name: "t1.%y%j.%H%M_7_2_1_1"
   - title: 367
     bands:
       r: "3"
       g: "6"
       b: "7"
       p: "1"
     name: "t1.%y%j.%H%M_3_6_7"
  a1:
   mapper:
     30: aqua_modis_bt30_*_alaska_1000.tif
     31: aqua_modis_bt31_*_alaska_1000.tif
     true_color: aqua_modis_true_color_*_alaska_250.tif
     1: aqua_modis_vis01_*_alaska_250.tif
     1_500: aqua_modis_vis01_*_alaska_500.tif
     2: aqua_modis_vis02_*_alaska_250.tif
     2_500: aqua_modis_vis02_*_alaska_500.tif
     3: aqua_modis_vis03_*_alaska_500.tif
     4: aqua_modis_vis04_*_alaska_500.tif
     5: aqua_modis_vis05_*_alaska_500.tif
     7: aqua_modis_vis07_*_alaska_500.tif
   single:
   - title: true_color
     band: true_color
     name: "a1.%y%j.%H%M_true_color"
   - title: thermal
     band: "31"
     name: "a1.%y%j.%H%M_31"
   combinations:
   - title: landcolor
     bands:
       r: "7"
       g: "2_500"
       b: "1_500"
       p: "1"
     name: "a1.%y%j.%H%M_7_2_1_1"
limits:
  processor: 1
