configs:
  default:
    grid: 203
    options: ' --grid-coverage 0  --source-name UAF '
    p2g_config: uaf_awips_backend.ini
    save:
    - UAF_AWIPS_metop*_avhrr_band[12345]*
driver: $POLAR2GRID_HOME/bin/avhrr2awips.sh
limits:
  processor: 2
