mphr:
  disposition_mode: O
  instrument_model: 1
  processing_center: RUSx
  processing_major_version: 2
  processing_minor_version: 0
  processing_mode: N
  product_type: hrp
  receiving_ground_station: RUS
