processing:
  atms: 
    save:
      - "*.nc"
      - "*.nc.gz" 
    driver: "mirs2awips.sh -g 203_10km --grid-coverage 0 -p rain_rate sea_ice snow_cover tpw swe clw"
    p2g_backend: "mirs_awips_backend.ini"
  amsu:
    save:
      - "*.nc"
      - "*.nc.gz"
    driver: "mirs2awips.sh -g 203_10km --grid-coverage 0 -p rain_rate sea_ice snow_cover tpw swe clw"
    p2g_backend: "mirs_awips_backend.ini"

