processing:
  npp: 
    save:
      - "NPR-MIRS-IMG*.nc"
      - "NPR-MIRS-SND*.nc"
    driver: "run_mirs.bash  -v -f -s npp "
  noaa20:
    save:
      - "NPR-MIRS-IMG*.nc"
      - "NPR-MIRS-SND*.nc"
    driver: "run_mirs.bash  -v -f -s n20 "
  metop-b:
    save:
      - "*.nc"
      - "*.nc"
    driver: "run_mirs.bash -res HI -f -v -s metopB " 
  metop-c:
    save:
      - "*.nc"
      - "*.nc"
    driver: "run_mirs.bash -res HI -f -v -s metopC "
  noaa18:
    save:
      - "*.nc"
      - "*.nc"
    driver: "run_mirs.bash -res HI -f -v -s n18 "
  noaa19:
    save:
      - "*.nc"
      - "*.nc"
    driver: "run_mirs.bash  -res HI -f -v -s n19 "
