processing:
  metop-b:
    driver: 'run_mirs.bash -r HI -d /cspp/dyno/mirs -p 6 -v  '
    save:
    - '*.nc'
    - '*.nc'
  metop-c:
    driver: 'run_mirs.bash -r HI -d /cspp/dyno/mirs -p 6 -v  '
    save:
    - '*.nc'
    - '*.nc'
  noaa18:
    driver: 'run_mirs.bash -r HI -d /cspp/dyno/mirs -p 6 -v  '
    save:
    - '*.nc'
    - '*.nc'
  noaa19:
    driver: 'run_mirs.bash  -r HI -d /cspp/dyno/mirs -p 6 -v  '
    save:
    - '*.nc'
    - '*.nc'
  noaa20:
    driver: 'run_mirs.bash  -v -d /cspp/dyno/mirs -p 6 '
    save:
    - NPR-MIRS-IMG*.nc
    - NPR-MIRS-SND*.nc
  noaa21:
    driver: 'run_mirs.bash  -v -d /cspp/dyno/mirs -p 6 '
    save:
    - NPR-MIRS-IMG*.nc
    - NPR-MIRS-SND*.nc
  npp:
    driver: 'run_mirs.bash  -v -d /cspp/dyno/mirs -p 6  '
    save:
    - NPR-MIRS-IMG*.nc
    - NPR-MIRS-SND*.nc
