processing:
  atms: 
    save:
      - "NPR-MIRS-IMG*.nc"
      - "NPR-MIRS-SND*.nc"
    driver: "run_mirs.bash  -v -s npp "
  metop-b:
    save:
      - "*.nc"
      - "*.nc"
    driver: "run_mirs.bash -res LO -v -s metopB " 
  noaa18:
    save:
      - "*.nc"
      - "*.nc"
    driver: "run_mirs.bash -res LO -v -s n18 "
  noaa19:
    save:
      - "*.nc"
      - "*.nc"
    driver: "run_mirs.bash  -res LO -v -s n19 "
