driver: "$POLAR2GRID_HOME/bin/modis2awips.sh"
driver_crefl: "$POLAR2GRID_HOME/bin/crefl2awips.sh"
configs:
  default: 
   options: " "
   grid: 203
   save: "UAF*"
   p2g_config: "uaf_awips_backend.ini"
limits:
  processor: 2
