configs:
  default:
    driver: mod14
    options: -tv
    output: '%Y%m%d.%H%M.mod14.hdf'
    output_note: The platform is pre-pended on the front of the output filrename pattern.
    save:
    - '*mod14.hdf'
    - '*mod14.hdf.txt'
    txt_driver: fireloc
