configs:
  a1: /opt/rt-stps/config/aqua.xml
  gcomw: /opt/rt-stps/config/GCOM-W1.xml
  noaa20: /opt/rt-stps/config/jpss1.xml
  noaa21: /opt/rt-stps/config/jpss2.xml
  npp: /opt/rt-stps/config/npp.xml
  t1: /opt/rt-stps/config/terra.xml
rtstps_driver: /opt/rt-stps/bin/batch.sh
source:
  gilmore: /gluster/cache/antenna/gilmore
  uafgina: /gluster/cache/antenna/uafgina
