configs:
  atms:
    driver: atms_sdr.sh
    options: '-l -z '
    rdr_glob: RATMS-RNSCA*.h5
  cris:
    driver: cris_sdr.sh
    options: '-l -z -f '
    rdr_glob: RCRIS-RNSC*.h5
  viirs:
    driver: viirs_sdr.sh
    options: ' -g -l '
    rdr_glob: RNSCA-RVIRS*.h5
env: $CSPP_SDR_HOME/cspp_sdr_env.sh
limits:
  processor: 1
