uafgina:
  ftp:
    dir: /dbingest/fairbanks/
    host: ftp.ssec.wisc.edu
    options: -F -B 12582912
  glob:
  - RNCSA*h5
  - RCRIS*h5
  - RATMS*h5
uafgina-test:
  ftp:
    dir: /dbingest/fairbanks/
    host: 192.168.56.31
    options: -F -B 12582912
  glob:
  - RNCSA*h5
  - RCRIS*h5
  - RATMS*h5
