---
uafgina-test:
  ftp:
    host: 192.168.56.31
    dir:  /dbingest/fairbanks/
  glob:
    - RNCSA*h5
    - RCRIS*h5
    - RATMS*h5
uafgina:
  ftp:
    host: ftp.ssec.wisc.edu
    dir:  /dbingest/fairbanks/
  glob:
    - RNCSA*h5
    - RCRIS*h5
    - RATMS*h5

