driver: "/opt/modis/polar2grid/polar2grid-swbundle-2.0.0rc10/bin/modis2awips.sh"
driver_crefl: "/opt/modis/polar2grid/polar2grid-swbundle-2.0.0rc10/bin/crefl2awips.sh"
configs:
  default: 
   options: " "
   grid: 203
   save: "UAF*"
   p2g_config: "uaf_awips_backend.ini"
limits:
  processor: 2
