processing:
  save:
    - "[at]1*.cal500.hdf"
    - "[at]1*.cal250.hdf"
    - "[at]1*.cal1000.hdf"
    - "[at]1*.geo.hdf"
    - "[AT]*.L1A_LAC"
    - "[AT]*.L1B_HKM"
    - "[AT]*.L1B_QKM"
    - "[AT]*.GEO"
  t1:
   l1_driver: "modis_L1A.py --startnudge=0 --stopnudge=0 "
   geo_driver: "modis_GEO.py -v --threshold=80"
   l1b_driver: "modis_L1B.py"
   destripe: "/opt/modis/destripe/run_modis_destripe.csh terra"
   pds: "*001.PDS"
   update_luts: "update_luts.py terra -v"
  a1:
   l1_driver: "modis_L1A.py --startnudge=0 --stopnudge=0 "
   geo_driver: "modis_GEO.py -a aqua_att -e aqua_eph --verbose --threshold=80 -n "
   l1b_driver: "modis_L1B.py"
   destripe: "/opt/modis/destripe/run_modis_destripe.csh aqua"
   gbad: "/opt/modis/gbad/wrapper/gbad/run aqua.gbad.pds P1540957*001.PDS aqua.gbad_eph aqua_eph aqua.gbad_att aqua_att"
   pds: "P1540064*001.PDS"
   update_luts: "update_luts.py aqua -v"
modis_tools_setup: "/opt/modis/setup.bash"

