configs:
  default: 
   polar2_grid_options: "--adaptive-dnb"
   grid_file: "config/viirs_geotiff_grids.grd" 
   igrid: "alaska_300"
   mgrid: "alaska_600"
   polar2grid_driver: "viirs2gtiff.sh"
   atm_polar2grid_driver: "crefl2gtiff.sh"
   dnb:
     save: "npp_viirs_dnb_adaptive*_alaska_600.tif"
     name: "npp.%y%j.%H%M_DNB.tif"
   combinations:
   - title: natural_color
     bands:
       r: "I03"
       g: "I02"
       b: "I01"
     name: "npp.%y%j.%H%M_I03_I02_I01"
     stretch: "-ndv '0.99995..1' -ndv 0.0 -linear-stretch 128 50 -outndv 0 "
   single_bands:
   - title: thermal
     band: "I05"
     name: "npp.%y%j.%H%M_I05"
     stretch:  "-ndv '0.99995..1' -ndv 0.0 -linear-stretch 128 50 -outndv 0 "
limits:
  processor: 1
